### ISSUE TITLE
Bumphunter repo not updated with Bioconductor

### ISSUE THREAD

**Issue by lcolladotor** [ririzarr/bumphunter#9]
Hi,

I noticed that currently `bumphunter` hosted here uses version 1.9.4 as shown at https://github.com/ririzarr/bumphunter/blob/4460617ca2974f2a76cf0051557f7ef4b3aebeb3/DESCRIPTION#L2 but using Bioc-devel the current version from `bumphunter` is 1.11.3.

Let me know if I should submit PR https://github.com/ririzarr/bumphunter/pull/8 somewhere else.

Best,
Leo

**Comment by martinaryee** [comment]
Thanks for pointing this out. The git/svn mirror is now fixed and the Github and Bioconductor repos are in sync
